# Site settings
title: My Awesome Site
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome site where I blog about my adventures in coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima theme settings
minima:
  skin: dark # Use "dark" for dark mode theme provided by Minima

# Author settings
author:
  name: Your Name
  email: your-email@example.com

# Social media settings (optional)
twitter_username: yourusername
github_username:  yourusername

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Plugins (if you need additional plugins)
plugins:
  - jekyll-seo-tag
